version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    networks:
      - webnet
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - webnet

networks:
  webnet:
